name: Prettier-Config Release Please
on:
  push:
    branches: [main]
    paths: [packages/prettier-config/**]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          default-branch: main
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          monorepo-tags: true
          bump-minor-pre-major: true
          path: packages/prettier-config
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"deps","section":"Dependencies"},{"type":"revert","section":"Reverts"},{"type":"docs","section":"Documentation"},{"type":"style","section":"Styles","hidden":true},{"type":"chore","section":"Miscellaneous Chores","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":true},{"type":"test","section":"Tests","hidden":true},{"type":"ci","section":"Continuous Integration","hidden":true}]'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: yarn install --immutable
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        run: yarn workspace @pinetwork-js/prettier-config npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}